media: 'assets/uploads'
content:
  - name: posts
    label: Posts
    type: collection
    path: '_posts'
    view:
      fields: [ title, date, published ]
    fields:
      - name: published
        label: Published
        type: boolean
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: image
        label: Image
        type: image
      - name: body
        label: Body
        type: rich-text
