repository: akhyarrh/akhyarrh.github.io

gems:
  - jekyll-assets
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

name:        "AkhyarRH"
description: "Hungry, Young, Wild, and Free"
url:         "https://akhyarrh.github.io"
author:
  name:  "Akhyar Rahman Hidayat"
  email: "akhyarrh@gmail.com"

timezone: Asia/Jakarta

host: localhost

permalink: /post/:title/

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Rakefile
  - README.md
  - script
  - vendor

sass:
  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  ignore:
    envs: [local]

# jekyll seo tag
title: AkhyarRH

# per-post
author: akhyarrh

# sitewide
twitter:
  username: akhyarrh

facebook:
  admins: 100000001003810

webmaster_verifications:
  google: "sV2248YCZVyLu6nhz72znzNoCUhSfCqwiCEjUO-Kiu8"
#  bing: 1234
  alexa: "gXuVtj4bXDWiVB_ihCJijNBQNj8"
#  yandex: 1234

logo: /assets/img/logo.png

lang: id_ID

# plugin: jekyll-assets
assets:
  prefix: "/assets"

  features:
    integrity: true
