# Ref:
#
# https://help.github.com/articles/configuring-jekyll/
# https://jekyllrb.com/docs/configuration/

timezone: Asia/Makassar

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: 'dark'

title: AkhyarRH
subtitle: Jurnal Online
description: >
  Seperti sebuah blog pada umumnya.
  Kebanyakan berisi tentang front-end, user experience,
  dan accessibility (a11y).
url: https://akhyar.js.org
baseurl: ""
repository: akhyarrh/akhyarrh.github.io
lang: id
locale: id-ID
logo: "/assets/logo.png"
og_image: "/assets/img/og-image-default.png"
name: "M Akhyar Rahman H"

comments:
  provider               : staticman_v2
  staticman:
    branch               : source
    endpoint             : https://staticman3.herokuapp.com/v3/entry/github/
reCaptcha:
    enabled: true
    siteKey: "6LdvJhUTAAAAAGWXMLZRgp8gwgx1uV7qCNMKVpa7"
    secret: "KB0jjJ5SOecKWaqYua/VjIF1OU3WtPKEXsDp2HMXXZG0Itmhqko5xtlpq7x93G4JaC+E9HeKST157sCZZ1tu1SoKhNQvj885JrxYOSiQXh7ZBDSak0uMlDWdGDdI5sEJrGopyRP/tavNe3uXT0FxLDwpDjofjXwmE1HgX35tq3ZL8i4qDQaAnzUGrT0oVHMbDOFGnQGkToUIxdc8uK0GvDVOCT7GrqmhZQJwkMAxhFEa8hcQg98IAyqc4ce+aJ1WA5pckjfCEocdv6rQKqGP9sBQEs9nEn8IZN9ijNTVX9w69Z3eYvNJefe+jOUzv0HJQktlfF25REvyeYm0hwPCAQ=="
search                   : true # true, false (default)
#search_full_content      : # true, false (default)

# Social Sharing
twitter:
  username               : akhyarrh
  card                   : summary_large_image
facebook:
  publisher              : https://facebook.com/akhyarrh

social:
  name                   : M. Akhyar Rahman H.
  links:
    - https://twitter.com/akhyarrh
    - https://github.com/akhyarrh

# Analytics
analytics:
  provider               : google-universal
  google:
    tracking_id          : UA-36665422-2
    anonymize_ip         : true

# SEO Related
webmaster_verifications:
  google : sV2248YCZVyLu6nhz72znzNoCUhSfCqwiCEjUO-Kiu8
  bing   : E9A1908DCAA52A63BF7B5F67DB05745D
  alexa  : gXuVtj4bXDWiVB_ihCJijNBQNj8
  #yandex :
naver_site_verification  : 6317134cb9bef4388b660148341705f37c442045

# Site Author
author:
  name             : "M. Akhyar Rahman H."
  twitter          : akhyarrh
  github           : akhyarrh
  lastfm           : akhyarrh
  links:
    - label: Feed
      icon: "fas fa-fw fa-rss"
      url: "/feed.xml"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/akhyarrh"
    - label: "GitHub"
      icon: "fab fa-fw fa-github-alt"
      url: "https://github.com/akhyarrh"
    - label: Last.fm
      icon: "fab fa-fw fa-lastfm"
      url: "https://last.fm/user/akhyarrh"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

permalink: /:title/
paginate: 8

show_drafts: false
future:      false
unpublished: false

exclude:
  - CNAME
  - Gemfile*
  - LICENSE
  - Makefile
  - Rakefile
  - README.md
  - vendor
  - staticman.yml
  - netlify.toml

sass:
  style: compressed

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      show_date: true
      read_time: true
      comments: true
      share: true
      related: true
      classes: wide
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      classes: wide
  - scope:
      path: ""
      type: tag
    values:
      author_profile: false
      comments: false
      classes: wide
  - scope:
      path: ""
      type: category
    values:
      author_profile: false
      comments: false
      classes: wide

# https://help.github.com/articles/configuring-jekyll-plugins/#default-plugins
plugins:
  #
  # Plugins below are enabled by default on github pages
  # I write them down here only for documentation purpose
  # more info see:
  # https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#plugins
  #
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-data
  - jekyll-include-cache
  - jekyll-target-blank
  - jekyll-loading-lazy
  - jekyll-pwa-workbox
  - jekyll-minifier

markdown: CommonMarkGhPages

#comment-post: https://docs.google.com/forms/d/e/1FAIpQLSdK2gNXrbEDYdLVXQczAgKaSCkPS--w4nGc_AJopcwlZMOIwQ
#comment-read: https://docs.google.com/spreadsheets/d/1txcAELxvQ0XiPlIYtLB4m5lBqc25I6EYRi5LmTzI1MA
#comment-post-fields: [ entry.676535420, entry.240716117, entry.185139534]

optional_front_matter:
  remove_originals: true

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

jekyll-mentions: https://twitter.com

target-blank:
  rel: nofollow

commonmark:
  options: ["SMART", "FOOTNOTES", "STRIKETHROUGH_DOUBLE_TILDE"]
  extensions: ["strikethrough", "autolink", "table"]

jekyll-minifier:
  exclude: ["*.xml", "*.txt", "*.webmanifest"]
  uglifier_args:
    harmony: true

pwa:
  #sw_src_filepath: service-worker.js # Optional
  #sw_dest_filename: service-worker.js # Optional
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 10 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "/**/*.{js,json,css}"
    - "/**/*.{ico,jpg,jpeg,png,svg,webp}"
    - "/**/*.html"
  precache_glob_ignores: # Optional
    - "sw-register.js"
    - "service-worker.js"
    - "assets/css/*.map"
    - "/assets/js/_main.js"
    - "/assets/js/lunr/lunr.js"
    - "/assets/js/lunr/lunr-gr.js"
    - "/assets/js/plugins/**/*"
    - "/assets/js/vendor/**/*"

# prose.io
prose:
  rooturl: '_posts'
  siteurl: 'https://akhyar.js.org/'
  relativeLinks: 'https://akhyar.js.org/links.jsonp'
  media: 'assets/uploads'
  metadata:
    _posts:
      - name: "published"
        field:
          element: "checkbox"
          value: false

      - name: "title"
        field:
          element: "text"
          label: "Title"

      - name: "date"
        field:
          element: "text"
          label: "Published Date"
          value: CURRENT_DATETIME

      - name: "last_modified_at"
        field:
          element: "text"
          label: "Modified Date"
          placeholder: CURRENT_DATETIME

      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "This image displayed & used as SEO image. Higher priority than Teaser Image."

      - name: "teaser_image"
        field:
          element: "text"
          label: "Teaser Image"
          help: "This image not displayed & not used as SEO image. Not used if Image already exist."

      - name: "categories"
        field:
          element: "multiselect"
          label: "Categories"
          alterable: true
          options: "https://akhyar.js.org/categories.jsonp?callback=categories"

      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          alterable: true
          options: "https://akhyar.js.org/tags.jsonp?callback=tags"
