gems:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap

name:        "akhyarrh's"
description: "Blogger • Freak • Gamer • Geek"
url:         "http://walutisme.com"
author:
  name:  "Akhyar Rahman Hidayat"
  email: "akhyarrh@gmail.com"
  uri:   "https://twitter.com/akhyarrh"

timezone: Asia/Jakarta

host: localhost

permalink: /post/:title
relative_permalinks: true

paginate: 10
paginate_path: /page/:num

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - package.json
  - Rakefile
  - README.md
  - vendor
  # exclude markdown writer files on gh-pages
  # used only on local
  - categories.json
  - posts.json
  - tags.json

sass:
  style: compressed

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - tables
    - autolink
    - disable_indented_code_blocks
    - strikethrough
    - highlight
    - quote

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  ignore:
    envs: [local]

prose:
  rooturl: _posts
  ignore:
    - _includes
    - _layouts
    - _sass
    - assets
    - _config-local.yml
    - _config.yml
    - _mdwriter.cson
    - categories.json
    - CNAME
    - Gemfile
    - Gemfile.lock
    - humans.txt
    - index.html
    - LICENSE
    - links.jsonp
    - posts.json
    - Rakefile
    - README.md
    - tags.json
  siteurl: http://walutisme.com
  media: assets/img
  relativeLinks: http://walutisme.com/links.jsonp
  metadata:
    _drafts:
      - name: 'title'
        field:
          element: text
          label: 'Title'
      - name: 'date'
        field:
          element: hidden
          value: $CURRENT_DATETIME
      - name: 'tags'
        field:
          element: text
          label: Tag(s)
          value: []
          placeholder: [tag1, tag2, tag3, ...]
    _posts:
      - name: 'title'
        field:
          element: text
          label: 'Title'
      - name: 'date'
        field:
          element: hidden
          value: $CURRENT_DATETIME
      - name: 'tags'
        field:
          element: text
          label: Tag(s)
          value: []
          placeholder: [tag1, tag2, tag3, ...]
