repository: akhyarrh/akhyarrh.github.io
gems:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-github-metadata

name:        "akhyarrh's"
description: "Blogger • Freak • Gamer • Geek"
url:         "http://walutisme.com"
author:
  name:  "Akhyar Rahman Hidayat"
  email: "akhyarrh@gmail.com"
  uri:   "https://twitter.com/akhyarrh"

timezone: Asia/Jakarta

host: localhost

permalink: /post/:title
relative_permalinks: true

paginate: 5
paginate_path: /page/:num

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Rakefile
  - README.md
  - script
  - vendor

sass:
  style: compressed

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - tables
    - autolink
    - disable_indented_code_blocks
    - strikethrough
    - highlight
    - quote

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  ignore:
    envs: [local]

excerpt_separator: "<!--more-->"

prose:
  rooturl: _posts
  siteurl: http://walutisme.com
  media: assets/img
  relativeLinks: http://walutisme.com/links.jsonp
  metadata:
    _posts:
      - name: 'title'
        field:
          element: text
          label: 'Title'
      - name: 'tags'
        field:
          element: multiselect
          label: Tag(s)
          options: 'http://walutisme.com/tags.jsonp'
