[context.production]
  publish = "_site/this/path/dont/exist/"

[context.deploy-preview]
  command = "bundle exec jekyll build --trace && npx @divriots/jampack ./_site"
  publish = "_site/"
  environment = { JEKYLL_ENV = "production" }
