name: Build and Deploy to master branch

on:
  push:
    branches:
      - source
  schedule:
    - cron: '0 0 1 * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - run: gem install bundler
      - run: bundle config path vendor/bundle
      - run: bundle install --jobs 4 --retry 3
      - run: bundle exec rake build

      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          publish_branch: master
          publish_dir: ./_site
          cname: akhyar.js.org
          force_orphan: true
          exclude_assets: '.github,assets/css/*.map,assets/js/_main.js,assets/js/lunr/lunr.js,assets/js/lunr/lunr-gr.js,assets/js/plugins/**/*,assets/js/vendor/**/*'
