name: Ping search engine after Jekyll site build & every week

on:
  page_build:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bundle exec rake ping
