name: Build and test after push/PR on source branch

on:
  push:
    branches:
      - source
  pull_request:
    branches:
      - source

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
  
      - uses: actions/setup-node@v3
        with:
         node-version: '18'
         
      - run: npm install
      - run: gem install bundler

      - run: bundle install --jobs 4 --retry 3
      - run: bundle exec rake test
