name: Build and test after push/PR on source branch

on:
  push:
    branches:
      - source
  pull_request:
    branches:
      - source

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - run: gem install bundler
      - run: bundle config path vendor/bundle
      - run: bundle install --jobs 4 --retry 3
      - run: bundle exec rake test
